-- Script de carga inicial de dados para a tabela Funcionario
-- Região: BR (Brasil)

INSERT INTO funcionario (id, nome, email, genero, regiao) VALUES
(1, 'João Silva', 'joao.silva@email.com', 'Masculino', 'BR'),
(2, 'Maria Santos', 'maria.santos@email.com', 'Feminino', 'BR'),
(3, 'Pedro Oliveira', 'pedro.oliveira@email.com', 'Masculino', 'BR'),
(4, 'Ana Costa', 'ana.costa@email.com', 'Feminino', 'BR'),
(5, 'Carlos Pereira', 'carlos.pereira@email.com', 'Masculino', 'BR'),
(6, 'Juliana Ferreira', 'juliana.ferreira@email.com', 'Feminino', 'BR'),
(7, 'Roberto Alves', 'roberto.alves@email.com', 'Masculino', 'BR'),
(8, 'Fernanda Lima', 'fernanda.lima@email.com', 'Feminino', 'BR'),
(9, 'Ricardo Souza', 'ricardo.souza@email.com', 'Masculino', 'BR'),
(10, 'Patricia Rocha', 'patricia.rocha@email.com', 'Feminino', 'BR'),
(11, 'Bruno Martins', 'bruno.martins@email.com', 'Masculino', 'BR'),
(12, 'Camila Ribeiro', 'camila.ribeiro@email.com', 'Feminino', 'BR'),
(13, 'Lucas Gomes', 'lucas.gomes@email.com', 'Masculino', 'BR'),
(14, 'Amanda Dias', 'amanda.dias@email.com', 'Feminino', 'BR'),
(15, 'Felipe Carvalho', 'felipe.carvalho@email.com', 'Masculino', 'BR'),
(16, 'Larissa Araujo', 'larissa.araujo@email.com', 'Feminino', 'BR'),
(17, 'Gabriel Mendes', 'gabriel.mendes@email.com', 'Masculino', 'BR'),
(18, 'Beatriz Nunes', 'beatriz.nunes@email.com', 'Feminino', 'BR'),
(19, 'Rafael Barbosa', 'rafael.barbosa@email.com', 'Masculino', 'BR'),
(20, 'Isabela Monteiro', 'isabela.monteiro@email.com', 'Feminino', 'BR'),
(21, 'Thiago Cardoso', 'thiago.cardoso@email.com', 'Masculino', 'BR'),
(22, 'Mariana Teixeira', 'mariana.teixeira@email.com', 'Feminino', 'BR'),
(23, 'Daniel Freitas', 'daniel.freitas@email.com', 'Masculino', 'BR'),
(24, 'Vanessa Campos', 'vanessa.campos@email.com', 'Feminino', 'BR'),
(25, 'André Rodrigues', 'andre.rodrigues@email.com', 'Masculino', 'BR'),
(26, 'Renata Moreira', 'renata.moreira@email.com', 'Feminino', 'BR'),
(27, 'Marcos Cunha', 'marcos.cunha@email.com', 'Masculino', 'BR'),
(28, 'Tatiana Ramos', 'tatiana.ramos@email.com', 'Feminino', 'BR'),
(29, 'Eduardo Lopes', 'eduardo.lopes@email.com', 'Masculino', 'BR'),
(30, 'Cristina Azevedo', 'cristina.azevedo@email.com', 'Feminino', 'BR'),
(31, 'Gustavo Machado', 'gustavo.machado@email.com', 'Masculino', 'BR'),
(32, 'Priscila Rezende', 'priscila.rezende@email.com', 'Feminino', 'BR'),
(33, 'Henrique Barros', 'henrique.barros@email.com', 'Masculino', 'BR'),
(34, 'Adriana Moura', 'adriana.moura@email.com', 'Feminino', 'BR'),
(35, 'Vinicius Castro', 'vinicius.castro@email.com', 'Masculino', 'BR'),
(36, 'Sabrina Pires', 'sabrina.pires@email.com', 'Feminino', 'BR'),
(37, 'Rodrigo Duarte', 'rodrigo.duarte@email.com', 'Masculino', 'BR'),
(38, 'Leticia Fonseca', 'leticia.fonseca@email.com', 'Feminino', 'BR'),
(39, 'Leandro Tavares', 'leandro.tavares@email.com', 'Masculino', 'BR'),
(40, 'Raquel Guimaraes', 'raquel.guimaraes@email.com', 'Feminino', 'BR'),
(41, 'Diego Morais', 'diego.morais@email.com', 'Masculino', 'BR'),
(42, 'Simone Vasconcelos', 'simone.vasconcelos@email.com', 'Feminino', 'BR'),
(43, 'Igor Siqueira', 'igor.siqueira@email.com', 'Masculino', 'BR'),
(44, 'Monica Brito', 'monica.brito@email.com', 'Feminino', 'BR'),
(45, 'Paulo Nascimento', 'paulo.nascimento@email.com', 'Masculino', 'BR'),
(46, 'Sandra Correia', 'sandra.correia@email.com', 'Feminino', 'BR'),
(47, 'Fabio Matos', 'fabio.matos@email.com', 'Masculino', 'BR'),
(48, 'Carla Pinheiro', 'carla.pinheiro@email.com', 'Feminino', 'BR'),
(49, 'Alexandre Coelho', 'alexandre.coelho@email.com', 'Masculino', 'BR'),
(50, 'Daniela Macedo', 'daniela.macedo@email.com', 'Feminino', 'BR');

